# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greenhouse_conditions.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bgreenhouse_conditions.proto\"I\n GreenhouseConditionsSubscription\x12\x13\n\x0bgreenhouses\x18\x01 \x03(\t\x12\x10\n\x08\x63lientID\x18\x02 \x01(\x05\"\xfc\x01\n\nConditions\x12\x12\n\ngreenhouse\x18\x01 \x01(\t\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x12\x10\n\x08humidity\x18\x03 \x01(\x02\x12\x12\n\nis_daytime\x18\x04 \x01(\x08\x12\x15\n\x05light\x18\x05 \x03(\x0b\x32\x06.Light\x12\x13\n\x04soil\x18\x06 \x03(\x0b\x32\x05.Soil\x12\x11\n\tco2_level\x18\x07 \x01(\x02\x12\x16\n\x0enitrogen_level\x18\x08 \x01(\x02\x12\x1e\n\nplant_type\x18\t \x01(\x0e\x32\n.PlantType\x12(\n\x0f\x66\x65rtilizer_type\x18\n \x01(\x0e\x32\x0f.FertilizerType\"1\n\x05Light\x12\x11\n\tintensity\x18\x01 \x01(\x02\x12\x15\n\x05\x63olor\x18\x02 \x01(\x0e\x32\x06.Color\"0\n\x04Soil\x12\x16\n\x0emoisture_level\x18\x01 \x01(\x02\x12\x10\n\x08pH_level\x18\x02 \x01(\x02*0\n\x05\x43olor\x12\x07\n\x03RED\x10\x00\x12\x08\n\x04\x42LUE\x10\x01\x12\t\n\x05WHITE\x10\x02\x12\t\n\x05GREEN\x10\x03*;\n\tPlantType\x12\n\n\x06\x46LOWER\x10\x00\x12\r\n\tVEGETABLE\x10\x01\x12\x08\n\x04HERB\x10\x02\x12\t\n\x05\x46RUIT\x10\x03*F\n\x0e\x46\x65rtilizerType\x12\x0b\n\x07ORGANIC\x10\x00\x12\r\n\tINORGANIC\x10\x01\x12\n\n\x06LIQUID\x10\x02\x12\x0c\n\x08GRANULAR\x10\x03\x32i\n\x14GreenhouseConditions\x12Q\n\x1dSubscribeGreenhouseConditions\x12!.GreenhouseConditionsSubscription\x1a\x0b.Conditions0\x01\x42\"\n\x03genB\x19GreenhouseConditionsProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greenhouse_conditions_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\003genB\031GreenhouseConditionsProtoP\001'
  _globals['_COLOR']._serialized_start=462
  _globals['_COLOR']._serialized_end=510
  _globals['_PLANTTYPE']._serialized_start=512
  _globals['_PLANTTYPE']._serialized_end=571
  _globals['_FERTILIZERTYPE']._serialized_start=573
  _globals['_FERTILIZERTYPE']._serialized_end=643
  _globals['_GREENHOUSECONDITIONSSUBSCRIPTION']._serialized_start=31
  _globals['_GREENHOUSECONDITIONSSUBSCRIPTION']._serialized_end=104
  _globals['_CONDITIONS']._serialized_start=107
  _globals['_CONDITIONS']._serialized_end=359
  _globals['_LIGHT']._serialized_start=361
  _globals['_LIGHT']._serialized_end=410
  _globals['_SOIL']._serialized_start=412
  _globals['_SOIL']._serialized_end=460
  _globals['_GREENHOUSECONDITIONS']._serialized_start=645
  _globals['_GREENHOUSECONDITIONS']._serialized_end=750
# @@protoc_insertion_point(module_scope)
